### PR TITLE
Ditch unused files in root dir

### PR DESCRIPTION
**Pull request by alkc**
# Description

This minor update removes a bunch of outdated and unused files from the root dir of the repo. 

The gatk ref creation process has been converted to a markdown file and moved to `docs/`

## Type of change

- [x] Patch

# Checklist:

- [x] I have performed a self-review of my code
- [x] My changes generate no new warnings (Keep an eye on `.nextflow.log` !)
- [x] I have updated the CHANGELOG
- [x] The latest commit in the master branch is tagged
      with the correct version number

## Patch

- [x] Stub run completes without errors or new warnings

## [Optional] Additional information

I've not dived into the scripts and singularity dirs. That's a separate issue. 

One thing that remains to be done in the root dir is to merge the deploy scripts into one. 

# Post-merge

- [ ] The `master` branch has been tagged with the new version number.

### CODE REVIEW

**Comment by alkc** [comment]
I'll move the deploy scripts into their own dir.

Which are the utility nf files?

**Comment by Jakob37** [comment]
> Which are the utility nf files?

I was thinking about `gatk.nf`, `mito.nf`, `rescore.nf`, `sv_only.nf`

**Comment by Jakob37** [comment]
These seems to be free-standing tiny pipelines not part of the main one. I guess these are only rarely run.

**Comment by alkc** [comment]
> > Which are the utility nf files?
> 
> I was thinking about `gatk.nf`, `mito.nf`, `rescore.nf`, `sv_only.nf`


Jaha! I've already nuked those after checking with Viktor

**Comment by Jakob37** [comment]
> > > Which are the utility nf files?
> > 
> > 
> > I was thinking about `gatk.nf`, `mito.nf`, `rescore.nf`, `sv_only.nf`
> 
> Jaha! I've already nuked those after checking with Viktor

Even better 💣

**Comment by alkc** [comment]
Both onco and wgs finish their stub runs w/o issues. Merging this!

**Pull request merged**
