### PR TITLE
Add new gene_panel JSON to avoid adding removed gene panels to our scout YAMLs

### LINKED ISSUE #209: Don't load removed panels with new cases
There is no need for loading cases with removed panels. It just causes clutter and confusion for the geneticists in Scout.

### PR DESCRIPTION
**Pull request by alkc**
# Description and reviewer info

This update changes the scout.gene_panel JSON path to a reduced JSON that only contains the data for active gene panels, thereby fixing the addition of dead/removed gene panels to our scout yaml files.

The reduced JSON is just a collection of panels filtered on the fields `hidden` and `is_archived`.

## Gene panel backup script

The new JSON is generated by a new script on lennart and added to the worker crontab with the same settings as the old gene panel back up script.

In short, it fetches the most recent versions of all gene panels in our scout production gene_panel collection, keeps all that are not hidden or archived, and saves a JSON of reduced panel objects (keeping only panel_name, institute, version and _id).

```
/data/bnf/scripts/save-active-scout-gene-panels.py
```

The update removes the following list of panels from future wgs cases:

```
Albinism                            
Arftlig_cancer                      
Blodnings_trombostillstand          
Ciliopati                           
Hjartmissbildning                   
Hudavvikelse                        
Hyperlipidemi                       
Hypogonadotrop_hypogonadism         
Immunbrist_upprepade_infektioner    
Jarnomsattningsstorning             
Komplex-kardiologi                  
Kraniofacial_avvikelse              
Metabol_sjukdom                     
Njursjukdom                         
Osteogenesis-imperfecta             
PAH-HHT-CM-AVM                      
PanelAppPediatricCardiomyopathy     
Stord_konsutveckling                
Syndrom_HNS                         
Synnedsattning                      
Utvecklingsstorning                 
ataxi-core                          
chicap-studien-actionable           
chicap-studien-clinical             
cmt-neuropati-core                  
hereditar-leukemi                   
hsp-core                            
panel-app-intellectual-disability-v3
panelapp-intellectual-disability    
```

closes #209

## Type of change

- [ ] Documentation
- [ ] Patch
- [x] Minor change
- [ ] Major change 

# Checklist

- [ ] Self-review of my code
- [ ] Update the CHANGELOG
- [ ] Tag the latest commit (vX.Y.Z format)
- [ ] Log samples used for testing in the `Verification_samples_log` Excel sheet

## Documentation
- [ ] At least one other person has reviewed my changes (not required for trivial changes)

## Major / Minor change
- [x] create_yml creates valid gene_panel values for oncov2-0 scout yamls
- [x] create_yml creates valid gene_panel values for wgs scout yaml
- [ ] Stub run completes without errors or new warnings
- [x] `onco` run finishes without any new warnings/errors and the results can 
       be loaded into scout
- [x] `wgs` single run finishes without any new warnings/errors and the results 
       can be loaded into scout
- [x] `wgs` trio run finishes without any new warnings/errors and the results 
       can be loaded into scout
- [ ] At least one other person has reviewed and approved my code
- [ ] I have made corresponding changes to the documentation (software versions, etc.)

# Test/review documentation

## Review performed by

- [ ] Alexander
- [ ] Jakob
- [ ] Paul
- [ ] Ryan
- [ ] Viktor

(Add if missing)

## Testing performed by

- [x] Alexander
- [ ] Jakob
- [ ] Paul
- [ ] Ryan
- [ ] Viktor

## post deployment tasls

- [ ] Set up gene panel dump script as a daily job on lennart/worker, link to /fs1/pipelines wgs bin

### CODE REVIEW

**Comment by alkc** [comment]
Confirmed that scout YAML looks as it should for wgs

**Comment by alkc** [comment]
Test procedure for YAML generation involved carrying over `.command.sh` from live run into dev environment, as the script is dependent on whether it's run in production/dev.

**Comment by alkc** [comment]
wgs trio YAML can be loaded into scout, but the gene dump script needs more adjusting as some deleted panels still make it through.

**Comment by alkc** [comment]
I've confirmed that YAMLs for both wgs and onco can be loaded into scout proper. I've confirmed that panels marked as "deleted" in wgs cases no longer appear for the test cases in scout.

Confirmed that onco cases look as they should.

**Comment by Jakob37** [comment]
Do we want to version control this script? Either in the bnf-infrastructure or here. Would it not make sense to include this in `bin/reference_tools` ?

**Comment by Jakob37** [comment]
Here, are you sure the `temp_file` is done writing before starting the copying? As the file handle still is open.

```
with tempfile.NamedTemporaryFile(mode="w", delete=True) as temp_file:

        LOG.debug("Dumping aggregated result to %s", temp_file.name)
        temp_file.write(bson.json_util.dumps(result))  # Write each document on a new line

        today = date.today().isoformat()
        remote_filepath = f"{REMOTE_OUTPUT_DIR}scout_gene_panels_active_{today}.json"
        LOG.debug("final remote_filepath: %s", remote_filepath)
        copy_panel_dump_to_remote(temp_file.name, remote_filepath)
```

https://stackoverflow.com/questions/51300181/is-it-necessary-to-call-flush-method-of-file-handler-in-python

Talking about things I don't know so well here. But might make sense to either close the fh (i.e. unindenting) before copying? Or running `temp_file.flush()`

**Comment by Jakob37** [comment]
Update log - the process is restoring, but the log says it is backing  up

```
        subprocess.run(restore_symlink_command, check=True)
        LOG.info("Successfully backed up old symlink to %s.bkp", REMOTE_LATEST_SYMLINK_PATH)
```

**Comment by Jakob37** [comment]
I wonder if there would be a point in using the ssh library Viktor used last year 🤔 To use a dedicated library instead of subprocess. Maybe not, this seems to work nicely enough.

**Comment by Jakob37** [comment]
You use `sys.exit`, but have forgotten to import the `sys` library

**Comment by Jakob37** [comment]
Test running it (repointing to my home dir) I see a bunch of entries have either numbers or hashes as panel names:

```
{
    "institute": "CMD",
    "_id": {
      "$oid": "5df2b4249756be569e04ef1b"
    },
    "panel_name": "384",
    "version": 2
  },
```

```
  {
    "institute": "CMD",
    "_id": {
      "$oid": "5df2b4299756be569e04ef24"
    },
    "panel_name": "553f94b4bb5a1616e5ed4595",
    "version": 1.9
  },
```

Is this expected?

**Review by Jakob37 — APPROVED** [review]
👌

**Comment by alkc** [comment]
Moves script into this repo. Made some more changes. Gonna do another quick onco run to see if everything still works as it should.

**Comment by alkc** [comment]
I've confirmed that that onco run completes without errors. I've confirmed that the new JSON-generating python script sets correct read permissions so that `worker` and friends can read the file on /fs1/. 

Merging in a bit.

**Pull request merged**
