### PR TITLE
Add stubs

### PR DESCRIPTION
**Pull request by ryanjameskennedy**
Delectable stubs were added to the world renowned wgs pipeline of CMD in order for dry-runs and versions of software used herein.

### CODE REVIEW

**Comment by ViktorHy** [comment]
why did you add a bunch of publishdir to processes that don't need it?

**Comment by ryanjameskennedy** [comment]
I needed them to publish the version files. My apologies for not changing it back.

**Comment by ViktorHy** [comment]
I added changes to master. Added stubs for the new processes generated for mito-qc. Fixed the test-output publishdir which in some cases were not needed. versions.yml is now published in ${OUTDIR}/versions instead. Added correct patterns to processes that did not actually capture any *versions.yml output as their patterns only admitted specific output. 

I have tested running stub-runs with the new code. Works just fine.

**Review by ViktorHy — APPROVED** [review]

**Comment by ViktorHy** [comment]
Since I made some changes to the code I would like @ramsainanduri to also look over the last two commits

**Comment by ViktorHy** [comment]
Nvm, this code does not work. Please @ryanjameskennedy run this in non-stub mode and make sure it works. You have borked all shell code snippets. You are mixing script-statements and shell statements variable standards.

**Comment by ryanjameskennedy** [comment]
Fixed and tested it on a human sample! Feel free to test yourself. I got the following warning:
```
WARN: Failed to publish file: /mnt/beegfs/nextflow/ryan-wgs-test.wgs_test_dev/36/2127b00535726642ad433673c6425c/compound_finder_versions.yml; to: /fs1/results_dev/wgs/versions/compound_finder_versions.yml
```
But the `compound_finder_versions.yml` is in the `publishDir`. I think the version file should be changed from `${task.process}_versions.yml` to `${id}_${task.process}_versions.yml`. I think this will prevent the warning as it's probably because the samples in the trio are all trying to write the `versions.yml` file at the same time.

**Comment by ViktorHy** [comment]
We discussed this in my office, just adding something to remember the discussion:

My thought was to have a list of versions locked with pipeline version. And as such only produce versions.yaml when we'd want to. This would then be added to readthedocs as a list of software versions.

**Comment by ViktorHy** [comment]
testing this a final time, and will merge once it passes.

**Review by ViktorHy — APPROVED** [review]

**Comment by ViktorHy** [comment]
I will resolve the merging issues. Good job with stubs m8

**Comment by Jakob37** [comment]
Me na d

**Comment by ramsainanduri** [comment]
Me and Jakob discussed about the stubs. He is working on it.

**Comment by Jakob37** [comment]
Closing this one and opening a new (draft for now) PR in #85 to keep things focused

**Pull request closed without merging**
