### PR TITLE
Jw/update cadd

### LINKED ISSUE #103: Fix the CADD to use version 1.6 (or 1.7)
Looks like the current CADD container built from the following repository: https://github.com/Clinical-Genomics-Lund/CADD-container is claimed to be 1.6, but actually is 1.5.

We should look over this and make sure that the latest version of CADD is used (1.6 at the moment of writing).

We could also consider whether the Galaxy container could be used for this:

https://depot.galaxyproject.org/singularity/cadd-scripts%3A1.6--0

### PR DESCRIPTION
**Pull request by Jakob37**
# Description

What is changed? What is the result of the changes?

Close #103 

## Type of change

- [x] Minor change

# Checklist:

- [x] My code follows the [style guidelines for NF pipelines at CMD](http://mtlucmds1.lund.skane.se/wiki/doku.php?id=nextflow&s[]=nextflow#code_style_at_cmd)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings (Keep an eye on `.nextflow.log` !)
- [x] I have updated the CHANGELOG
- [ ] The latest commit in the master branch is tagged
      with the correct version number

## Minor change
- [x] Stub run completes without errors or new warnings
- [x] `onco` run finishes without any new warnings/errors and the results can 
       be loaded into scout
- [x] `wgs` single run finishes without any new warnings/errors and the results 
      can be loaded into scout
- [x] `wgs` trio run finishes without any new warnings/errors and the results 
       can be loaded into scout
- [ ] At least one other person has reviewed and approved my code
- [x] I have made corresponding changes to the documentation

## [Optional] Are there any post-deployment tasks we need to perform?

 - [ ] Task/link to issue 1
 - [ ] Task/link to issue 2
 - [ ] ...
 
# Instructions for the reviewers

## How to test the changes

1. Step 1
2. Step 2

## [Optional] Additional information

# Review

## Review performed by:
- Reviewer 1: Alexander Koc, (@alkc )  
    
## Testing performed by:
- Jakob Willforss, (@Jakob37 )

# Post-merge
- [ ] The `master` branch has been tagged with the new version number.

### CODE REVIEW

**Comment by Jakob37** [comment]
Not ready for review, but relevant for the VEP work.

I'll run tests for this one tonight and tomorrow. Hopefully results are similar ...

**Comment by Jakob37** [comment]
v1.7 db prepared, md5sum checked, and tabix indexed

Doing a full run of all PR tests over night. Hopefully things will look good tomorrow and it will be ready for merge into the validation branch.

**Comment by Jakob37** [comment]
I am running the stubs as well, but guessing that should look OK. Other testing looks fine.

Ready for review @alkc

**Review by alkc — APPROVED** [review]
Looks good!

**Comment by Jakob37** [comment]
Oops, missed updating the version in the table (maybe that should be in the checklist template!)

Will fix it directly in the validation branch

**Comment by Jakob37** [comment]
No, wait, this is a db update, the CADD version is for the indel scripts

**Pull request merged**
